### ISSUE TITLE
Add reference from `AM.ElasticSearch.Extensions.Logging` nuget to source

### ISSUE THREAD

**Issue by dzmitry-lahoda** [amccool/AM.Extensions.Logging.ElasticSearch#11]
Please add source reference
https://www.nuget.org/packages/AM.ElasticSearch.Extensions.Logging/1.0.39

Github fails to find `AM.ElasticSearch.Extensions.Logging` by name.

**Comment by amccool** [comment]
any chance you could PR that change?

**Comment by amccool** [comment]
we cant rename to `ElasticSearch.Extensions.Logging` on nuget.org, as its a `locked` name.   `Elasticsearch.` is owned by Elasticsearch.   Not sure when they started enforcing ownership on the top level names.  have to find the email they sent me (or the docs)

**Comment by dzmitry-lahoda** [comment]
As variant may add prefix `Unofficial` as generic prefix for owned namespaces.
```
Unofficial.Microsoft.AspNetCore.SignalR.Protocols.MessagePack.Unity
```

**Comment by amccool** [comment]
nuget name changed to:   https://www.nuget.org/packages/AM.Extensions.Logging.ElasticSearch and a source link was added
